"""add_archived_at_to_research_project

Revision ID: 01f3ef12e7b7
Revises: f45210d8b288
Create Date: 2026-08-17 14:50:58.643584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f3ef12e7b7'
down_revision: Union[str, Sequence[str], None] = 'f45210d8b288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_project', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_project', 'archived_at')
    # ### end Alembic commands ###
