"""create_capability_selection_and_gap_tables

Revision ID: 02200aeca916
Revises: 01f3ef12e7b7
Create Date: 2026-08-18 05:09:40.291348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02200aeca916'
down_revision: Union[str, Sequence[str], None] = '01f3ef12e7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_gap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('investigation_step_id', sa.Integer(), nullable=False),
    sa.Column('scientific_requirement', sa.Text(), nullable=False),
    sa.Column('required_input_types', sa.JSON(), nullable=True),
    sa.Column('required_output_types', sa.JSON(), nullable=True),
    sa.Column('reason_unavailable', sa.Text(), nullable=False),
    sa.Column('possible_resolution', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_step_id'], ['investigation_step.id'], name=op.f('fk_capability_gap_investigation_step_id_investigation_step'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_capability_gap_project_id_research_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_gap'))
    )
    op.create_index(op.f('ix_capability_gap_investigation_step_id'), 'capability_gap', ['investigation_step_id'], unique=False)
    op.create_index(op.f('ix_capability_gap_project_id'), 'capability_gap', ['project_id'], unique=False)
    op.create_table('capability_selection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_step_id', sa.Integer(), nullable=False),
    sa.Column('selected_capability_id', sa.Integer(), nullable=True),
    sa.Column('eligible_capability_ids', sa.JSON(), nullable=True),
    sa.Column('selection_method', sa.String(length=64), nullable=False),
    sa.Column('scientific_rationale', sa.Text(), nullable=True),
    sa.Column('rejected_alternatives', sa.JSON(), nullable=True),
    sa.Column('known_limitations', sa.Text(), nullable=True),
    sa.Column('researcher_status', sa.String(length=32), nullable=False),
    sa.Column('llm_provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_step_id'], ['investigation_step.id'], name=op.f('fk_capability_selection_investigation_step_id_investigation_step'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_capability_id'], ['scientific_capability.id'], name=op.f('fk_capability_selection_selected_capability_id_scientific_capability'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_selection'))
    )
    op.create_index(op.f('ix_capability_selection_investigation_step_id'), 'capability_selection', ['investigation_step_id'], unique=True)
    op.create_index(op.f('ix_capability_selection_selected_capability_id'), 'capability_selection', ['selected_capability_id'], unique=False)
    op.add_column('scientific_capability', sa.Column('input_types', sa.JSON(), nullable=True))
    op.add_column('scientific_capability', sa.Column('output_types', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scientific_capability', 'output_types')
    op.drop_column('scientific_capability', 'input_types')
    op.drop_index(op.f('ix_capability_selection_selected_capability_id'), table_name='capability_selection')
    op.drop_index(op.f('ix_capability_selection_investigation_step_id'), table_name='capability_selection')
    op.drop_table('capability_selection')
    op.drop_index(op.f('ix_capability_gap_project_id'), table_name='capability_gap')
    op.drop_index(op.f('ix_capability_gap_investigation_step_id'), table_name='capability_gap')
    op.drop_table('capability_gap')
    # ### end Alembic commands ###
