"""add research question

Revision ID: 2a26772dfb70
Revises: de06c7ebeba0
Create Date: 2026-08-16 09:30:11.419354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a26772dfb70'
down_revision: Union[str, Sequence[str], None] = 'de06c7ebeba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_question_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('inferential_level', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_question_id'], ['research_question.id'], name=op.f('fk_research_question_parent_question_id_research_question')),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_research_question_project_id_research_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_question'))
    )
    op.create_index(op.f('ix_research_question_project_id'), 'research_question', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_question_project_id'), table_name='research_question')
    op.drop_table('research_question')
    # ### end Alembic commands ###
