"""add_b01_taxonomy_and_scope_fields_to_scientific_capability

Revision ID: 41d7e6e348ed
Revises: 02200aeca916
Create Date: 2026-08-18 09:41:58.958484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41d7e6e348ed'
down_revision: Union[str, Sequence[str], None] = '02200aeca916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scientific_capability', sa.Column('domain', sa.String(length=64), nullable=False, server_default='biodiversity_informatics'))
    op.add_column('scientific_capability', sa.Column('subdomain', sa.String(length=64), nullable=True))
    op.add_column('scientific_capability', sa.Column('ebv_dimension', sa.String(length=64), nullable=True))
    op.add_column('scientific_capability', sa.Column('capability_scope', sa.String(length=64), nullable=False, server_default='generic_core'))
    op.add_column('scientific_capability', sa.Column('is_generic', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    op.add_column('scientific_capability', sa.Column('scientific_maturity', sa.String(length=32), nullable=False, server_default='installed'))
    op.add_column('scientific_capability', sa.Column('expected_evidence_types', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_scientific_capability_capability_scope'), 'scientific_capability', ['capability_scope'], unique=False)
    op.create_index(op.f('ix_scientific_capability_domain'), 'scientific_capability', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scientific_capability', sa.Column('creates_dataset_version', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_scientific_capability_domain'), table_name='scientific_capability')
    op.drop_index(op.f('ix_scientific_capability_capability_scope'), table_name='scientific_capability')
    op.drop_column('scientific_capability', 'expected_evidence_types')
    op.drop_column('scientific_capability', 'scientific_maturity')
    op.drop_column('scientific_capability', 'is_generic')
    op.drop_column('scientific_capability', 'capability_scope')
    op.drop_column('scientific_capability', 'ebv_dimension')
    op.drop_column('scientific_capability', 'subdomain')
    op.drop_column('scientific_capability', 'domain')
    # ### end Alembic commands ###
