"""add research_plan table

Revision ID: 58a7d999399f
Revises: 5f1525830241
Create Date: 2026-08-16 16:29:17.900902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a7d999399f'
down_revision: Union[str, Sequence[str], None] = '5f1525830241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('brainstorming_session_id', sa.Integer(), nullable=True),
    sa.Column('parent_plan_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('model_provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brainstorming_session_id'], ['brainstorming_session.id'], name=op.f('fk_research_plan_brainstorming_session_id_brainstorming_session')),
    sa.ForeignKeyConstraint(['parent_plan_id'], ['research_plan.id'], name=op.f('fk_research_plan_parent_plan_id_research_plan')),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_research_plan_project_id_research_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_plan'))
    )
    op.create_index(op.f('ix_research_plan_brainstorming_session_id'), 'research_plan', ['brainstorming_session_id'], unique=False)
    op.create_index(op.f('ix_research_plan_parent_plan_id'), 'research_plan', ['parent_plan_id'], unique=False)
    op.create_index(op.f('ix_research_plan_project_id'), 'research_plan', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_plan_project_id'), table_name='research_plan')
    op.drop_index(op.f('ix_research_plan_parent_plan_id'), table_name='research_plan')
    op.drop_index(op.f('ix_research_plan_brainstorming_session_id'), table_name='research_plan')
    op.drop_table('research_plan')
    # ### end Alembic commands ###
