"""add provenance to research_question and hypothesis

Revision ID: 5f1525830241
Revises: a349eb1c6a4e
Create Date: 2026-08-16 16:11:37.247368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1525830241'
down_revision: Union[str, Sequence[str], None] = 'a349eb1c6a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hypothesis', sa.Column('source', sa.String(length=32), nullable=True))
    op.add_column('hypothesis', sa.Column('brainstorming_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_hypothesis_brainstorming_session_id'), 'hypothesis', ['brainstorming_session_id'], unique=False)
    op.create_foreign_key(op.f('fk_hypothesis_brainstorming_session_id_brainstorming_session'), 'hypothesis', 'brainstorming_session', ['brainstorming_session_id'], ['id'])
    op.add_column('research_question', sa.Column('source', sa.String(length=32), nullable=True))
    op.add_column('research_question', sa.Column('brainstorming_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_research_question_brainstorming_session_id'), 'research_question', ['brainstorming_session_id'], unique=False)
    op.create_foreign_key(op.f('fk_research_question_brainstorming_session_id_brainstorming_session'), 'research_question', 'brainstorming_session', ['brainstorming_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_research_question_brainstorming_session_id_brainstorming_session'), 'research_question', type_='foreignkey')
    op.drop_index(op.f('ix_research_question_brainstorming_session_id'), table_name='research_question')
    op.drop_column('research_question', 'brainstorming_session_id')
    op.drop_column('research_question', 'source')
    op.drop_constraint(op.f('fk_hypothesis_brainstorming_session_id_brainstorming_session'), 'hypothesis', type_='foreignkey')
    op.drop_index(op.f('ix_hypothesis_brainstorming_session_id'), table_name='hypothesis')
    op.drop_column('hypothesis', 'brainstorming_session_id')
    op.drop_column('hypothesis', 'source')
    # ### end Alembic commands ###
