"""create_research_agenda_item_table

Revision ID: 76dae4d80cde
Revises: 58a7d999399f
Create Date: 2026-08-17 04:37:51.046078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76dae4d80cde'
down_revision: Union[str, Sequence[str], None] = '58a7d999399f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_agenda_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('origin_project_id', sa.Integer(), nullable=True),
    sa.Column('origin_research_plan_id', sa.Integer(), nullable=True),
    sa.Column('origin_result_id', sa.Integer(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('current_evidence', sa.Text(), nullable=True),
    sa.Column('known_limitations', sa.Text(), nullable=True),
    sa.Column('follow_up_opportunities', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['origin_project_id'], ['research_project.id'], name=op.f('fk_research_agenda_item_origin_project_id_research_project')),
    sa.ForeignKeyConstraint(['origin_research_plan_id'], ['research_plan.id'], name=op.f('fk_research_agenda_item_origin_research_plan_id_research_plan')),
    sa.ForeignKeyConstraint(['origin_result_id'], ['result.id'], name=op.f('fk_research_agenda_item_origin_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_agenda_item'))
    )
    op.create_index(op.f('ix_research_agenda_item_origin_project_id'), 'research_agenda_item', ['origin_project_id'], unique=False)
    op.create_index(op.f('ix_research_agenda_item_origin_research_plan_id'), 'research_agenda_item', ['origin_research_plan_id'], unique=False)
    op.create_index(op.f('ix_research_agenda_item_origin_result_id'), 'research_agenda_item', ['origin_result_id'], unique=False)
    op.create_index(op.f('ix_research_agenda_item_status'), 'research_agenda_item', ['status'], unique=False)
    op.create_index(op.f('ix_research_agenda_item_type'), 'research_agenda_item', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_agenda_item_type'), table_name='research_agenda_item')
    op.drop_index(op.f('ix_research_agenda_item_status'), table_name='research_agenda_item')
    op.drop_index(op.f('ix_research_agenda_item_origin_result_id'), table_name='research_agenda_item')
    op.drop_index(op.f('ix_research_agenda_item_origin_research_plan_id'), table_name='research_agenda_item')
    op.drop_index(op.f('ix_research_agenda_item_origin_project_id'), table_name='research_agenda_item')
    op.drop_table('research_agenda_item')
    # ### end Alembic commands ###
