"""add core scientific world model

Revision ID: 7b8843ef19be
Revises: 2a26772dfb70
Create Date: 2026-08-16 09:38:04.573149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8843ef19be'
down_revision: Union[str, Sequence[str], None] = '2a26772dfb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_key', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('selection_definition', sa.JSON(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('grouping_keys', sa.JSON(), nullable=True),
    sa.Column('manifest_uri', sa.String(length=1024), nullable=True),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_dataset_version_project_id_research_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_version')),
    sa.UniqueConstraint('version_key', name=op.f('uq_dataset_version_version_key'))
    )
    op.create_index(op.f('ix_dataset_version_project_id'), 'dataset_version', ['project_id'], unique=False)
    op.create_table('research_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_research_event_project_id_research_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_event'))
    )
    op.create_index(op.f('ix_research_event_created_at'), 'research_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_event_event_type'), 'research_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_research_event_project_id'), 'research_event', ['project_id'], unique=False)
    op.create_table('source_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_source_document_project_id_research_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_document'))
    )
    op.create_index(op.f('ix_source_document_identifier'), 'source_document', ['identifier'], unique=False)
    op.create_index(op.f('ix_source_document_project_id'), 'source_document', ['project_id'], unique=False)
    op.create_table('claim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('claim_type', sa.String(length=64), nullable=False),
    sa.Column('epistemic_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_claim_project_id_research_project')),
    sa.ForeignKeyConstraint(['question_id'], ['research_question.id'], name=op.f('fk_claim_question_id_research_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim'))
    )
    op.create_index(op.f('ix_claim_project_id'), 'claim', ['project_id'], unique=False)
    op.create_index(op.f('ix_claim_question_id'), 'claim', ['question_id'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('decision_type', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_decision_project_id_research_project')),
    sa.ForeignKeyConstraint(['question_id'], ['research_question.id'], name=op.f('fk_decision_question_id_research_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision'))
    )
    op.create_index(op.f('ix_decision_project_id'), 'decision', ['project_id'], unique=False)
    op.create_index(op.f('ix_decision_question_id'), 'decision', ['question_id'], unique=False)
    op.create_table('hypothesis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['research_question.id'], name=op.f('fk_hypothesis_question_id_research_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypothesis'))
    )
    op.create_index(op.f('ix_hypothesis_question_id'), 'hypothesis', ['question_id'], unique=False)
    op.create_table('analysis_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('estimand', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('exploratory', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], name=op.f('fk_analysis_plan_dataset_version_id_dataset_version')),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.id'], name=op.f('fk_analysis_plan_hypothesis_id_hypothesis')),
    sa.ForeignKeyConstraint(['question_id'], ['research_question.id'], name=op.f('fk_analysis_plan_question_id_research_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_plan'))
    )
    op.create_index(op.f('ix_analysis_plan_dataset_version_id'), 'analysis_plan', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_analysis_plan_hypothesis_id'), 'analysis_plan', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_analysis_plan_question_id'), 'analysis_plan', ['question_id'], unique=False)
    op.create_table('claim_edge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_claim_id', sa.Integer(), nullable=False),
    sa.Column('target_claim_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('qualification', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_claim_id'], ['claim.id'], name=op.f('fk_claim_edge_source_claim_id_claim')),
    sa.ForeignKeyConstraint(['target_claim_id'], ['claim.id'], name=op.f('fk_claim_edge_target_claim_id_claim')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_edge'))
    )
    op.create_index(op.f('ix_claim_edge_source_claim_id'), 'claim_edge', ['source_claim_id'], unique=False)
    op.create_index(op.f('ix_claim_edge_target_claim_id'), 'claim_edge', ['target_claim_id'], unique=False)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.id'], name=op.f('fk_prediction_hypothesis_id_hypothesis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction'))
    )
    op.create_index(op.f('ix_prediction_hypothesis_id'), 'prediction', ['hypothesis_id'], unique=False)
    op.create_table('analysis_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_plan_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('tool_version', sa.String(length=100), nullable=True),
    sa.Column('source_code_commit', sa.String(length=64), nullable=True),
    sa.Column('generated_code_hash', sa.String(length=64), nullable=True),
    sa.Column('container_image_digest', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('random_seeds', sa.JSON(), nullable=True),
    sa.Column('hardware_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_plan_id'], ['analysis_plan.id'], name=op.f('fk_analysis_run_analysis_plan_id_analysis_plan')),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], name=op.f('fk_analysis_run_dataset_version_id_dataset_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_run'))
    )
    op.create_index(op.f('ix_analysis_run_analysis_plan_id'), 'analysis_run', ['analysis_plan_id'], unique=False)
    op.create_index(op.f('ix_analysis_run_dataset_version_id'), 'analysis_run', ['dataset_version_id'], unique=False)
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('uri', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], name=op.f('fk_artifact_analysis_run_id_analysis_run')),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_artifact_project_id_research_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact'))
    )
    op.create_index(op.f('ix_artifact_analysis_run_id'), 'artifact', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_artifact_project_id'), 'artifact', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifact_sha256'), 'artifact', ['sha256'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('uncertainty', sa.JSON(), nullable=True),
    sa.Column('diagnostics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], name=op.f('fk_result_analysis_run_id_analysis_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result'))
    )
    op.create_index(op.f('ix_result_analysis_run_id'), 'result', ['analysis_run_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('analysis_run_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_role', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], name=op.f('fk_review_analysis_run_id_analysis_run')),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('fk_review_claim_id_claim')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.create_index(op.f('ix_review_analysis_run_id'), 'review', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_review_claim_id'), 'review', ['claim_id'], unique=False)
    op.create_table('evidence_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('validity_status', sa.String(length=32), nullable=False),
    sa.Column('independence_group', sa.String(length=100), nullable=True),
    sa.Column('inferential_level', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], name=op.f('fk_evidence_item_artifact_id_artifact')),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('fk_evidence_item_claim_id_claim')),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name=op.f('fk_evidence_item_result_id_result')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], name=op.f('fk_evidence_item_source_document_id_source_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_item'))
    )
    op.create_index(op.f('ix_evidence_item_artifact_id'), 'evidence_item', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_evidence_item_claim_id'), 'evidence_item', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_item_result_id'), 'evidence_item', ['result_id'], unique=False)
    op.create_index(op.f('ix_evidence_item_source_document_id'), 'evidence_item', ['source_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_item_source_document_id'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_result_id'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_claim_id'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_artifact_id'), table_name='evidence_item')
    op.drop_table('evidence_item')
    op.drop_index(op.f('ix_review_claim_id'), table_name='review')
    op.drop_index(op.f('ix_review_analysis_run_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_result_analysis_run_id'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_artifact_sha256'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_project_id'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_analysis_run_id'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_index(op.f('ix_analysis_run_dataset_version_id'), table_name='analysis_run')
    op.drop_index(op.f('ix_analysis_run_analysis_plan_id'), table_name='analysis_run')
    op.drop_table('analysis_run')
    op.drop_index(op.f('ix_prediction_hypothesis_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_claim_edge_target_claim_id'), table_name='claim_edge')
    op.drop_index(op.f('ix_claim_edge_source_claim_id'), table_name='claim_edge')
    op.drop_table('claim_edge')
    op.drop_index(op.f('ix_analysis_plan_question_id'), table_name='analysis_plan')
    op.drop_index(op.f('ix_analysis_plan_hypothesis_id'), table_name='analysis_plan')
    op.drop_index(op.f('ix_analysis_plan_dataset_version_id'), table_name='analysis_plan')
    op.drop_table('analysis_plan')
    op.drop_index(op.f('ix_hypothesis_question_id'), table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_index(op.f('ix_decision_question_id'), table_name='decision')
    op.drop_index(op.f('ix_decision_project_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_claim_question_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_project_id'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_source_document_project_id'), table_name='source_document')
    op.drop_index(op.f('ix_source_document_identifier'), table_name='source_document')
    op.drop_table('source_document')
    op.drop_index(op.f('ix_research_event_project_id'), table_name='research_event')
    op.drop_index(op.f('ix_research_event_event_type'), table_name='research_event')
    op.drop_index(op.f('ix_research_event_created_at'), table_name='research_event')
    op.drop_table('research_event')
    op.drop_index(op.f('ix_dataset_version_project_id'), table_name='dataset_version')
    op.drop_table('dataset_version')
    # ### end Alembic commands ###
