"""add_b01_metadata_and_decomposed_maturity_to_scientific_capability

Revision ID: 9141edf7efd4
Revises: 41d7e6e348ed
Create Date: 2026-08-18 10:10:31.373490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9141edf7efd4'
down_revision: Union[str, Sequence[str], None] = '41d7e6e348ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scientific_capability', sa.Column('knowledge_status', sa.String(length=32), nullable=False, server_default='known'))
    op.add_column('scientific_capability', sa.Column('availability', sa.String(length=32), nullable=False, server_default='installed'))
    op.add_column('scientific_capability', sa.Column('implementation_key', sa.String(length=100), nullable=True))
    op.add_column('scientific_capability', sa.Column('preconditions', sa.JSON(), nullable=True))
    op.add_column('scientific_capability', sa.Column('scientific_assumptions', sa.JSON(), nullable=True))
    op.add_column('scientific_capability', sa.Column('scientific_constraints', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scientific_capability', 'scientific_constraints')
    op.drop_column('scientific_capability', 'scientific_assumptions')
    op.drop_column('scientific_capability', 'preconditions')
    op.drop_column('scientific_capability', 'implementation_key')
    op.drop_column('scientific_capability', 'availability')
    op.drop_column('scientific_capability', 'knowledge_status')
    # ### end Alembic commands ###
