"""add brainstorming_session

Revision ID: a349eb1c6a4e
Revises: da6df95ef19c
Create Date: 2026-08-16 15:41:15.280534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a349eb1c6a4e'
down_revision: Union[str, Sequence[str], None] = 'da6df95ef19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brainstorming_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('initial_idea', sa.Text(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('model_provenance', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('research_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_brainstorming_session_project_id_research_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brainstorming_session'))
    )
    op.create_index(op.f('ix_brainstorming_session_project_id'), 'brainstorming_session', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brainstorming_session_project_id'), table_name='brainstorming_session')
    op.drop_table('brainstorming_session')
    # ### end Alembic commands ###
