"""create_scientific_capability_and_application_tables

Revision ID: d59b10cf9359
Revises: c5d264271c36
Create Date: 2026-08-17 10:31:42.070280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59b10cf9359'
down_revision: Union[str, Sequence[str], None] = 'c5d264271c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scientific_application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('host_environment', sa.String(length=255), nullable=False),
    sa.Column('invocation_type', sa.String(length=64), nullable=False),
    sa.Column('interface_url', sa.String(length=512), nullable=True),
    sa.Column('is_gpu_required', sa.Boolean(), nullable=False),
    sa.Column('execution_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scientific_application')),
    sa.UniqueConstraint('name', name=op.f('uq_scientific_application_name'))
    )
    op.create_index(op.f('ix_scientific_application_category'), 'scientific_application', ['category'], unique=False)
    op.create_table('scientific_capability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('capability_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_purpose', sa.Text(), nullable=False),
    sa.Column('scientific_tasks', sa.Text(), nullable=True),
    sa.Column('typical_duration', sa.String(length=64), nullable=True),
    sa.Column('reproducibility_level', sa.String(length=64), nullable=False),
    sa.Column('modifies_data', sa.Boolean(), nullable=False),
    sa.Column('creates_result', sa.Boolean(), nullable=False),
    sa.Column('creates_artifact', sa.Boolean(), nullable=False),
    sa.Column('creates_dataset_version', sa.Boolean(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('default_parameters', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['scientific_application.id'], name=op.f('fk_scientific_capability_application_id_scientific_application'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scientific_capability'))
    )
    op.create_index(op.f('ix_scientific_capability_application_id'), 'scientific_capability', ['application_id'], unique=False)
    op.create_index(op.f('ix_scientific_capability_capability_key'), 'scientific_capability', ['capability_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scientific_capability_capability_key'), table_name='scientific_capability')
    op.drop_index(op.f('ix_scientific_capability_application_id'), table_name='scientific_capability')
    op.drop_table('scientific_capability')
    op.drop_index(op.f('ix_scientific_application_category'), table_name='scientific_application')
    op.drop_table('scientific_application')
    # ### end Alembic commands ###
