"""add analysis run lifecycle

Revision ID: da6df95ef19c
Revises: 7b8843ef19be
Create Date: 2026-08-16 14:21:28.628476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6df95ef19c'
down_revision: Union[str, Sequence[str], None] = '7b8843ef19be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_run', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_run', 'started_at')
    # ### end Alembic commands ###
