"""create_investigation_planning_tables

Revision ID: f45210d8b288
Revises: d59b10cf9359
Create Date: 2026-08-17 14:01:21.408734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45210d8b288'
down_revision: Union[str, Sequence[str], None] = 'd59b10cf9359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_plan_generation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('research_plan_id', sa.Integer(), nullable=True),
    sa.Column('summary_rationale', sa.Text(), nullable=True),
    sa.Column('identified_uncertainties', sa.JSON(), nullable=True),
    sa.Column('model_provenance', sa.JSON(), nullable=True),
    sa.Column('context_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_investigation_plan_generation_project_id_research_project')),
    sa.ForeignKeyConstraint(['question_id'], ['research_question.id'], name=op.f('fk_investigation_plan_generation_question_id_research_question')),
    sa.ForeignKeyConstraint(['research_plan_id'], ['research_plan.id'], name=op.f('fk_investigation_plan_generation_research_plan_id_research_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_plan_generation'))
    )
    op.create_index(op.f('ix_investigation_plan_generation_project_id'), 'investigation_plan_generation', ['project_id'], unique=False)
    op.create_index(op.f('ix_investigation_plan_generation_question_id'), 'investigation_plan_generation', ['question_id'], unique=False)
    op.create_index(op.f('ix_investigation_plan_generation_research_plan_id'), 'investigation_plan_generation', ['research_plan_id'], unique=False)
    op.create_table('investigation_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('research_plan_id', sa.Integer(), nullable=True),
    sa.Column('generation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scientific_goal', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('step_type', sa.String(length=64), nullable=False),
    sa.Column('requires_capability', sa.Boolean(), nullable=False),
    sa.Column('requires_experiment', sa.Boolean(), nullable=False),
    sa.Column('required_operation', sa.Text(), nullable=True),
    sa.Column('expected_evidence', sa.Text(), nullable=True),
    sa.Column('completion_criteria', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('researcher_notes', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['investigation_plan_generation.id'], name=op.f('fk_investigation_step_generation_id_investigation_plan_generation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], name=op.f('fk_investigation_step_project_id_research_project')),
    sa.ForeignKeyConstraint(['question_id'], ['research_question.id'], name=op.f('fk_investigation_step_question_id_research_question')),
    sa.ForeignKeyConstraint(['research_plan_id'], ['research_plan.id'], name=op.f('fk_investigation_step_research_plan_id_research_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_step'))
    )
    op.create_index(op.f('ix_investigation_step_generation_id'), 'investigation_step', ['generation_id'], unique=False)
    op.create_index(op.f('ix_investigation_step_project_id'), 'investigation_step', ['project_id'], unique=False)
    op.create_index(op.f('ix_investigation_step_question_id'), 'investigation_step', ['question_id'], unique=False)
    op.create_index(op.f('ix_investigation_step_research_plan_id'), 'investigation_step', ['research_plan_id'], unique=False)
    op.create_index(op.f('ix_investigation_step_status'), 'investigation_step', ['status'], unique=False)
    op.create_index(op.f('ix_investigation_step_step_type'), 'investigation_step', ['step_type'], unique=False)
    op.create_table('investigation_step_dependency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_step_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_step_id'], ['investigation_step.id'], name=op.f('fk_investigation_step_dependency_depends_on_step_id_investigation_step'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['investigation_step.id'], name=op.f('fk_investigation_step_dependency_step_id_investigation_step'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_step_dependency')),
    sa.UniqueConstraint('step_id', 'depends_on_step_id', name='uq_step_dependency')
    )
    op.create_index(op.f('ix_investigation_step_dependency_depends_on_step_id'), 'investigation_step_dependency', ['depends_on_step_id'], unique=False)
    op.create_index(op.f('ix_investigation_step_dependency_step_id'), 'investigation_step_dependency', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_step_dependency_step_id'), table_name='investigation_step_dependency')
    op.drop_index(op.f('ix_investigation_step_dependency_depends_on_step_id'), table_name='investigation_step_dependency')
    op.drop_table('investigation_step_dependency')
    op.drop_index(op.f('ix_investigation_step_step_type'), table_name='investigation_step')
    op.drop_index(op.f('ix_investigation_step_status'), table_name='investigation_step')
    op.drop_index(op.f('ix_investigation_step_research_plan_id'), table_name='investigation_step')
    op.drop_index(op.f('ix_investigation_step_question_id'), table_name='investigation_step')
    op.drop_index(op.f('ix_investigation_step_project_id'), table_name='investigation_step')
    op.drop_index(op.f('ix_investigation_step_generation_id'), table_name='investigation_step')
    op.drop_table('investigation_step')
    op.drop_index(op.f('ix_investigation_plan_generation_research_plan_id'), table_name='investigation_plan_generation')
    op.drop_index(op.f('ix_investigation_plan_generation_question_id'), table_name='investigation_plan_generation')
    op.drop_index(op.f('ix_investigation_plan_generation_project_id'), table_name='investigation_plan_generation')
    op.drop_table('investigation_plan_generation')
    # ### end Alembic commands ###
